services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: postgres-pgvector
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=misuperpassword
      - POSTGRES_DB=vectordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # restart: unless-stopped

  cloudbeaver:
    image: dbeaver/cloudbeaver:25
    container_name: dbeaver
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
    restart: unless-stopped
    depends_on:
      - pgvector

volumes:
  postgres_data:
  cloudbeaver_workspace: